chore(typings): add interface Config['cors']
eggjs/egg-cors pull request #12
Opened 2018-04-08 12:05 UTC by waitingsong

usage:
// {app_root}/config/config.default.js

import { Config as CorsConfig } from 'egg-cors'

export default (appInfo: EggAppConfig) => {
  const config = <PowerPartial<EggAppConfig> & CorsConfig> {}
  // ...
  config.cors = {
    origin: '*',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS',
  }

  return config
}

##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Affected core subsystem(s)

##### Description of change

2018-04-08 12:07 UTC, waitingsong commented
usage:
```ts
// {app_root}/config/config.default.ts

import { Config as CorsConfig } from 'egg-cors'

export default (appInfo: EggAppConfig) => {
  const config = <PowerPartial<EggAppConfig> & CorsConfig> {}
  // ...
  config.cors = {
    origin: '*',
    allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH,OPTIONS',
  }

  return config
}
```

2018-04-08 12:07 UTC, atian25 requested changes

2018-04-08 12:07 UTC, atian25 commented on index.d.ts
> +declare module 'egg-cors' {
egg

2018-04-08 12:07 UTC, atian25 commented on index.d.ts
> +  export interface Config {
EggAppConfig

2018-04-08 12:07 UTC, atian25 commented on index.d.ts
> +  export interface Config {
要 merge 的。。。

2018-04-08 12:08 UTC, waitingsong commented on index.d.ts
> +  export interface Config {
哦。我以为那边不合并了

2018-04-08 12:09 UTC, atian25 commented on index.d.ts
> +  export interface Config {
是在这边写，但要用 merge 的语法。
然后应用层安装这个插件的时候，只需要 import 一下就自动合并了。

2018-04-08 12:13 UTC, waitingsong commented on index.d.ts
> +  export interface Config {
哦， 你是说把模块名改成 egg 吧

2018-04-08 12:15 UTC, waitingsong commented
不知道 fdf024b 这个写法可行否

2018-06-20 13:26 UTC, popomore approved these changes

2018-06-20 13:28 UTC, popomore commented
pkg.files 不需要改？

2018-06-21 00:31 UTC, atian25 commented
`npm pack` 验证了下，需要加 `pkg.files`

@waitingsong 再改下这个

2018-06-21 02:21 UTC, waitingsong commented
pkg.files 是啥。没明白

2018-06-21 03:41 UTC, atian25 commented
https://github.com/eggjs/egg-cors/blob/master/package.json#L8

这里要加下 index.d.ts ，否则不会被发布到 npm

2018-06-21 03:51 UTC, atian25 approved these changes

2018-07-11 12:53 UTC, fengmk2 approved these changes

2018-07-11 12:54 UTC, merged

2018-07-11 12:55 UTC, fengmk2 commented
2.1.0